# Generated by Django 2.2.4 on 2019-11-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20191110_1803'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact_group',
            table='contacts_groups',
        ),
    ]
