# Generated by Django 2.2.8 on 2020-05-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20191110_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_group',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
