# Generated by Django 2.2.4 on 2019-11-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190829_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='africastalking_sender_id',
        ),
    ]
