# Generated by Django 2.2.4 on 2019-11-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_africastalking_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='africastalking_sender_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
